# Generated by Django 5.0.7 on 2024-07-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length='255')),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
