# Generated by Django 5.0.7 on 2024-07-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idade',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='name',
        ),
    ]
